### ISSUE TITLE
probably needs a README and LICENSE/COPYING

### ISSUE THREAD

**Issue by willkg** [hylang/shyte#2]
This repository could do with a README and a LICENSE/COPYING file.

Re: README. I'm not entirely sure what this repository is. If someone can walk me through it, I can create a README and do a pr.

Re: LICENSE: Skimming the code, it says it's copyright 2013 Paul and licensed under the same terms as hy. That should be more explicit and less referential. Is it good enough to copy over the LICENSE file from the hy repository? If so, I can do a pr.

**Comment by paultag** [comment]
Yah, I actually split this out of hy its self, so it used to be in site/

This powers hylang.org 

BTW, you can leave my name out of it, everyone keeps copyright, nothings assigned :)

**Comment by willkg** [comment]
Sounds good! I'll do a pr of grave importance as soon as I can.

**Comment by paultag** [comment]
:heart:

**Comment by willkg** [comment]
In pull #3.
