### ISSUE TITLE
Consider renaming the module...

### ISSUE THREAD

**Issue by smandy** [hylang/shyte#5]
It's name has a homophone which is a profanity in a few English dialects. It might be offputting to some.

**Comment by paultag** [comment]
It's an inactive repo by a native English speaker from 6 years ago, I don't think it's worth a rename. 

Thanks though.

**Comment by Kodiologist** [comment]
This project is currently abandoned.

**Comment by Kodiologist** [comment]
@paultag Ha, jinx!

**Comment by smandy** [comment]
Ah okay.

Thanks.
